### PR TITLE
Added scope test in pom.xml

### PR DESCRIPTION
**Pull request by Anton20HD**
Added scope test in pom.xml

### CODE REVIEW

**Review by Viktormes — DISMISSED** [review]
Looks good.

**Review by xCandyFun — DISMISSED** [review]
Looks okay to me

**Comment by kappsegla** [comment]
What about assertj and mockito dependencies?

**Comment by Anton20HD** [comment]
> @Anton20HD What about assertj and mockito dependencies?

Thats right! Updated the pom.xml file now

**Review by Viktormes — APPROVED** [review]
Looks even better now. Good point on what was missing @kappsegla

**Pull request merged**
