### PR TITLE
Update java version

### PR DESCRIPTION
**Pull request by ErikaSignal**
Update Java version to 21 and some of the methods to newer methods that also looks cleaner.

### CODE REVIEW

**Review by cmatlak — APPROVED** [review]
Looks good and clean, easier to read

**Review by robinalfengard — CHANGES_REQUESTED** [review]
Good update, looks a lot cleaner! 

But there seems to be a problem with the build? I think the jacoco version in the project does not support java 21. Maybe it needs to be updated in the pom.xml to a newer version. 
https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by kappsegla** [comment]
Should also update java version in Dockerfile, since that is using 19-jre now.
`FROM eclipse-temurin:19-jre-jammy`

Can be done in this pullrequest but make sure to try to create a docker image locally and run it to make sure everything works. The dockerfile is used by our automatic release process so it must work. :)

The commands to build the image locally should be:

mvn verify
docker build --tag tag:version .

**Comment by ErikaSignal** [comment]
Thank you for the feedback! Updated the docker version now too and all is checked :D

**Review by robinalfengard — APPROVED** [review]
Updated jacoco version fixed previous issue :)

**Review by cmatlak — APPROVED** [review]
looks good with the version changes, all files seems to build succesfuly

**Pull request merged**
