### PR TITLE
Create issue-link.yml

### PR DESCRIPTION
**Pull request by williamDenStore**
I think a repo-token is requierd at row 15. But i'm not sure how to generate one 
EDIT: it seem to run fine without it. Which might mean a repo-token isn't required

### CODE REVIEW

**Comment by ArmanAlemirad** [comment]
Repo-token
according to the website you don't need one... 
I think that kappsegla can create repo-token due to setting access if that's necessary.

**Review by figgge — APPROVED** [review]
Looks good :)

**Review by ArmanAlemirad — APPROVED** [review]

**Comment by kappsegla** [comment]
I tried running this yml file in another repo and tried several ways of getting it to run with no luck. Doesn't seem to be triggered when opening a new pullrequest. Nothing happens at all? Anyone else managed to get it to work in a test repo?

**Comment by jLereback** [comment]
Closed for debugging

**Pull request closed without merging**
