### PR TITLE
Add delete feature

### PR DESCRIPTION
**Pull request by jLereback**
Add delete function, simple get function and tests

### CODE REVIEW

**Review by safstromo — APPROVED** [review]
God job!
Seems to work as intended :)

**Review by safstromo — COMMENTED** [review]
I dont think the get method is correct. 
If the key exixst it should just return the key. 
https://redis.io/commands/get/

im assuming this is the same get as #8

**Review by jonathanjonathan001 — COMMENTED** [review]
I don't know @safstromo , it seems to be correct to me https://redis.io/commands/get/
See where it says Return: Bulk string reply

**Review by jonathanjonathan001 — DISMISSED** [review]

**Comment by safstromo** [comment]
> I don't know @safstromo , it seems to be correct to me https://redis.io/commands/get/ See where it says Return: Bulk string reply

:+1:

**Review by safstromo — APPROVED** [review]

**Review by jonathanjonathan001 — APPROVED** [review]

**Review by Svartkettil — APPROVED** [review]
This looks good to me :)

**Pull request merged**
