### PR TITLE
156 databases are split so many commands dont work with lists

### PR DESCRIPTION
**Pull request by cchriss123**
HazeList is now reworked to save in the same database as the rest of the program.

### CODE REVIEW

**Review by RobertMili — APPROVED** [review]

**Review by RobertMili — APPROVED** [review]

**Review by kappsegla — COMMENTED** [review]
Code looks good and all command seems to do the right thing with the lists but when trying unit tests lpush and rpush seems to return the wrong value. They are supposed to return the length of the list for that key after doing the changes.

assertThat(pool.lpush("test", "first")).isEqualTo(1);
assertThat(pool.lpush("test", "second")).isEqualTo(2);

This will fail on the second line where lpush returns 1 but should be 2?

I verified this behavior against redis as a benchmark.

**Comment by cchriss123** [comment]
@kappsegla 

> @cchriss123 Code looks good and all command seems to do the right thing with the lists but when trying unit tests lpush and rpush seems to return the wrong value. They are supposed to return the length of the list for that key after doing the changes.
> 
> assertThat(pool.lpush("test", "first")).isEqualTo(1); assertThat(pool.lpush("test", "second")).isEqualTo(2);
> 
> This will fail on the second line where lpush returns 1 but should be 2?
> 
> I verified this behavior against redis as a benchmark.

Im probably misunderstanding something but from what I can tell it does that?

Screenshot 2023-02-25 at 13 23 55

**Comment by cchriss123** [comment]
> @cchriss123 Code looks good and all command seems to do the right thing with the lists but when trying unit tests lpush and rpush seems to return the wrong value. They are supposed to return the length of the list for that key after doing the changes.
> 
> assertThat(pool.lpush("test", "first")).isEqualTo(1); assertThat(pool.lpush("test", "second")).isEqualTo(2);
> 
> This will fail on the second line where lpush returns 1 but should be 2?
> 
> I verified this behavior against redis as a benchmark.

Good catch. It should be fixed now.

**Review by kappsegla — APPROVED** [review]
All tests are green and integration tests works as expected now.

**Pull request merged**
