### PR TITLE
185 refractor init methods from main to initialize

### PR DESCRIPTION
**Pull request by cmatlak**
Moved Auth methods to Auth class

### CODE REVIEW

**Review by TrungMa1 — APPROVED** [review]

**Comment by cmatlak** [comment]
thank you for the feedback, tests will be added. sometimes my trigger finger is faster than the brain

**Review by Mattan41 — DISMISSED** [review]
85.7% Coverage on New Code with the new tests

**Review by Danback — DISMISSED** [review]
Looks good to me, good job!

**Review by TrungMa1 — APPROVED** [review]
Well done!

**Comment by cmatlak** [comment]
this update should also solve remaining issues in #206 refactor-main i think

**Review by robinalfengard — DISMISSED** [review]
Should result in cleaner separation between Auth methods and Main, good job!

**Review by TrungMa1 — DISMISSED** [review]
Well done!

**Review by Danback — DISMISSED** [review]

**Review by robinalfengard — APPROVED** [review]
Changes looks good!

**Pull request merged**
