### PR TITLE
HazeDatabase: Change access modifiers to public and add parameters

### LINKED ISSUE #64: HazeDatabase, private methods and parameters missing
I think that the methods should be public in order for them to get accessed by other classes, and also add correct parameters to them.

### PR DESCRIPTION
**Pull request by jonathanjonathan001**
Also, remove static from fields (SonarLint complained).

See if you approve of the changes I made!

Fixes #64

### CODE REVIEW

**Comment by jonathanjonathan001** [comment]
SonarClouds code smells are understandable since we haven't implemented the methods yet!

**Review by MikaelEdwartz — APPROVED** [review]
Paramaters were left out intentionally for the implementer. Nice implementation

**Review by safstromo — APPROVED** [review]
👍

**Review by jLereback — COMMENTED** [review]
Looking good! :+1:

**Pull request merged**
