### PR TITLE
142-additional-tests-to-increase-code-coverage

### PR DESCRIPTION
**Pull request by ValentinaSukonina**
more tests added

### CODE REVIEW

**Comment by LudwigPersson** [comment]
Tests looks good and the tests cases are well-structured and cover different cases! Good job

**Review by LudwigPersson — COMMENTED** [review]
Tests looks good and the tests cases are well-structured and cover different cases! Good job

**Review by ErikaSignal — APPROVED** [review]
Works well and looks good!

**Review by Lucia560 — APPROVED** [review]
Good

**Pull request merged**
