### PR TITLE
Add command switch and command enum

### PR DESCRIPTION
**Pull request by cchriss123**
Fixes formating.
Add code.

Due to technical issues i decided to delete old branch and start a new one.
Fixes problem with old unsigned commit.
Fixes problem with bad uncompilable commit.
Fixes problem with 33 other commits that had snuck there way unto here that should not have ben here.
Fixes problem with push rejection after rebase.

### CODE REVIEW

**Review by safstromo — COMMENTED** [review]
I think you need to use a String as paramiter in the Commands switch for it to work, since the input we get are strings.
And then match string.valueof() in the switch.

Read more [here.](https://stackoverflow.com/questions/604424/how-to-get-an-enum-value-from-a-string-value-in-java)

**Comment by cchriss123** [comment]
Did big change. Need feedback on this.

@safstromo 
@MikaelEdwartz

**Review by wassimtajeddin — APPROVED** [review]
it looks much better

**Comment by safstromo** [comment]
Screenshot from 2023-02-14 08-41-24

This is what i mean with my earlier comment.

Maybe im missing something, or is it the from text method in Commad class where you are gonna convert the input to command?

**Comment by cchriss123** [comment]
@safstromo 
Im probably more confused than you are here haha.
The text in front of the command will be the String argument for a method call. I think they need to have one? 

In the latest commit you would have to type something like:
"commandSwitch.command(Command.valueOf("SET"));"
When you do the method call but I agree its much cleaner to have it in the switch method instead.

**Comment by cchriss123** [comment]
Unless I'm missing something, which is not only possible but also very likely, somewhere in the program we will have to split the Strings we receive from the user for example "LPUSH key1 Val2" so that LPUSH calls the method LPUSH and "key1 Val2" will be set as the placeholder text sended to the method called from the switch case and than probably spliced again into arguments sent into the LPUSH call.

**Comment by cchriss123** [comment]
@safstromo 
What do you think about just designing it like this instead of using ENUM?
Its a lot more easy to understand for me.

commandswitch

**Comment by safstromo** [comment]
> 

This is basically the same as what we have today in main.

Screenshot from 2023-02-14 13-18-32

The reasoning behind the enum was to lockdown all commands to constants to prevent misspelling and to easy maintain and read in the future.

Maybe we should just close this issue for now and come back in the future if needed?
Sorry for wasting your time.

**Pull request closed without merging**
