### PR TITLE
38 enum switch

### PR DESCRIPTION
**Pull request by cchriss123**
Adds Enum Commands and a commandHandler.

Not quite sure what commands to add.

### CODE REVIEW

**Review by cchriss123 — COMMENTED** [review]
Fixed line on last row

**Review by safstromo — CHANGES_REQUESTED** [review]
Looking good! We will just add commands later as they come!

Some issue templates seems to have snuck into this pull request please remove those :)

**Review by MikaelEdwartz — CHANGES_REQUESTED** [review]
Code looks good but I would suggest changing the name since we should avoid calling classes [handler](https://stackoverflow.com/questions/1866794/naming-classes-how-to-avoid-calling-everything-a-whatevermanager), besides the naming it looks like a solid start!

**Comment by kappsegla** [comment]
@cchriss123 There are two issue template files included in this commit? Looks like it doesn't belong with the enum java files?

**Review by cchriss123 — COMMENTED** [review]
I agree on the problem

**Comment by kappsegla** [comment]
> Yes they were not supposed to be there.

Looks like the problem with template files is solved now since we have merged these templates into main so they are synced with each other.

**Pull request closed without merging**
