### PR TITLE
Add log4j2 feature

### PR DESCRIPTION
**Pull request by VenuModi**
Added log4j2 dependency in pom.xml.
Created a log4j2 class with seperate methods for calling info, warn, error & debug that can be called in other classes. For now we wont save log messages in a file. But if we want to activate it, we can just uncomment the lines in log4j2.xml under the resources folder.

### CODE REVIEW

**Comment by VenuModi** [comment]
Closed the previous branch due to becoming too confusing

https://github.com/fungover/haze/pull/85

**Review by jonathanjonathan001 — DISMISSED** [review]

**Review by safstromo — DISMISSED** [review]

**Review by RehasLiamsi — APPROVED** [review]
Looks good

**Review by Viktormes — APPROVED** [review]
Looks fine.

**Review by RehasLiamsi — APPROVED** [review]
Looks good

**Pull request merged**
