### PR TITLE
Add log4j2 feature

### PR DESCRIPTION
**Pull request by VenuModi**
Added log4j2 dependency in pom.xml.
Created a log4j2 class with seperate methods for calling info, warn, error & debug that can be called in other classes. For now we wont save log messages in a file. But if we want to activate it, we can just uncomment the lines in log4j2.xml under the resources folder.

Rebase main into branch

### CODE REVIEW

**Review by RehasLiamsi — APPROVED** [review]

**Review by jonathanjonathan001 — CHANGES_REQUESTED** [review]
Maybe you should call the log4j2.java Log4j2.java with an upper-case L since it's a class.

**Review by safstromo — COMMENTED** [review]
Nice work!

What do you say about removing the logger path for a bit cleaner prints?
Screenshot from 2023-02-14 10-46-45
Screenshot from 2023-02-14 10-47-07

**Review by jonathanjonathan001 — APPROVED** [review]

**Review by Viktormes — APPROVED** [review]
Looks good.

**Comment by kappsegla** [comment]
@VenuModi Looks like one of the commits failed to be signed. To be able to merge with main all commits must be signed. What you can do is the following:
git fetch origin         # gets latest changes made to main
git switch 33-logging     # switch to your feature branch
git rebase main        # rebase your branch on main
# complete the rebase, fix merge conflicts, etc.
git push --force      # replace the branch on github

**Comment by VenuModi** [comment]
> Nice work!
> 
> What do you say about removing the logger path for a bit cleaner prints? Screenshot from 2023-02-14 10-46-45 Screenshot from 2023-02-14 10-47-07

Yes Good suggestion. I can do that and commit changes. :)

**Review by jonathanjonathan001 — COMMENTED** [review]
I see that you still have one commit that is not verified.

**Comment by kappsegla** [comment]
> 
Isn't this because logmanager is printing the classname from which the log methods are called? In this case all log messages will be from same class? An alternative solution is to add the following code to each class we have that needs logging:

`private static Logger logger = LogManager.getLogger(MyClassName.class);` 

and we can then do logging in that class with:
`logger.error("This is an error message");`

But in normal log messages that information can probably still be removed from the printing as @safstromo suggested and can be turned on when trying to do more advanced debugging?

**Pull request closed without merging**
